### ISSUE TITLE
'Incomplete' (Minimal) 'Half Done' (Things) Checkbox Missing and Does Not Trigger Menu

### ISSUE THREAD

**Issue by technotherion** [jaewonE/checkbox-styling-helper#5]
In both the Minimal and Things/S Checkbox CSS (Else), the Incomplete or Half Done status is missing from the options in the menu. 
Additionally, a line with the half done checkbox on it `- [/]` does not trigger opening the Checkbox dialogue when ':' is added to the line. I'm guessing that the `/` character is simply breaking the syntax.

**Comment by jaewonE** [comment]
The Half Done status was considered unnecessary and therefore was not included. However, since there are users who find it necessary, we will include it in the next update. Additionally, the Checkbox dialogue is currently triggered by "-:", "- :", and "- [ ] :". We will provide a hotkey command to enable the dialogue to trigger even when there are values inside the brackets.

**Comment by jaewonE** [comment]
In version 1.2.0, the following updates have been made:

1. Added five basic icons: number, unordered list, empty checkbox, half done, etc.
2. Provided a hot key to open the icon picker.(default: (Command + ;) on Mac / (Ctrl + ;) on Windows)
3. Enabled setting an icon via command even if there is already text on the current line.
4. Enabled changing an icon via command even if an icon is already set on the current line.
5. Allowed customization of the trigger.

Please update the plugin in the Obsidian Community Plugins: obsidian://show-plugin?id=checkbox-styling-helper

**Note!!**: To update the list of available icons, it is necessary to reset the data.json file. Before using, please change the theme to a different one (e.g., Else) in the plugin settings and then revert to the original theme to apply the updated icons.
